language: generic
script: bash ./deploy.sh
env:
  global:
    ENCRYPTION_LABEL: 44cecb45b4cf
branches:
  only:
    - master
deploy:
  provider: releases
  api_key:
    secure: DB+wygM281HfzEqOK9aXK1dTkCcJo1HW6GeJ/M9Zkm1ohoKB0tuJeJ7qFrvT+nmmhXlL3Nf9pNCgGVPc8HX8edYmFX/chn4sNLx2G4mwBX1jD/ibi1MYBA20TtGm2YyJwLFxEWXL12WoF3Dy5mQeZaWrzaFjKtwVvtm3NtpPVdKmobxZ0IsVxUhJP30rFsJKQXTBiAHCHkAl+o07GE86upVtUOFi0UC6XvGBd3nd7wwRqj4B3Uhv0jkmCSZQlUUhxwr5lAOA+7cmTsrwmxyEREse4i5XdJ79ODVCXMq+3xQvMXQiRKDK5yyQjKVWkeFVqo1gjbt9msuFTlK/sGroOUzvA3KA910005Fl2/TGOUj9lT9XR2ZqJ5zjp6FGj2MTGAxfVuyqfIbq+1tsBnNEqtHIMqUl1g+bhro0a5g79yxEsuuYCESpt4SNfAwbtv7P9Xdal6N4ctdaga8KZc2ndIFdlqA5IGw0/FzLVIlYDTz6Zeg7GT9d2hJ5JMQcdow9jJf52nZ/yqvkxWH4H+L/GNGXyRHuFvbxp/ZJTjXZXHk5v52diJfMw3p0rFvOrekWXasUgyc8CjNIyOvzvyjPWaA/TU/XKFLQbq2s94hBjmzkR09AApJD0GZyexbClyRKse5hhVI8BOvYqTuf1XLnSeBLrtq/4eK1vpWIeS+W564=
  file: dps
  skip_cleanup: true
  on:
    tags: true